Algoritmo "Variaveis"
Var
   Abacate, Melancia,TotalFrutasSacola: Inteiro
Inicio
   //Declarando variaveis
   Abacate <- 2
   Melancia <- 3

   TotalFrutasSacola <- Abacate + Melancia
   //Declaração variavel da soma

   //Trocando o valor da variavel Abacate
   Abacate <- 5
   
   //Somando novamente
   TotalFrutasSacola <- Abacate + Melancia
   
   //Imprimindo resultados
   Escreva(TotalFrutasSacola)

Fimalgoritmo